In [128]:
import pandas as pd
import matplotlib


df = pd.read_csv('F:/covid19.csv')
new_df = df.dropna()
print(new_df.to_string())

     Unnamed: 0           Country,Other  TotalCases   NewCases TotalDeaths
0             0                     USA  29,383,324    +12,619    529,515
1             1                   India  11,156,250    +16,927    157,471
3             3                  Russia   4,278,750    +10,535     87,348
6             6                   Spain   3,136,321     +6,137     70,247
7             7                   Italy   2,976,274    +20,884     98,635
8             8                  Turkey   2,734,836    +11,520     28,771
9             9                 Germany   2,466,366     +4,305     71,517
12           12                  Mexico   2,097,194     +7,913    187,187
13           13                  Poland   1,735,406    +15,698     44,360
14           14                    Iran   1,656,699     +8,525     60,353
16           16                 Ukraine   1,364,705     +7,235     26,397
17           17               Indonesia   1,353,834     +6,808     36,721
19           19                 Czechia   1,269,058    +16,642     20,941
22           22                   Chile     835,552     +3,040     20,704
23           23                 Romania     812,318     +4,278     20,586
24           24                Portugal     806,626       +979     16,430
25           25                  Israel     787,211     +1,993      5,797
26           26                 Belgium     774,344     +2,050     22,141
27           27                    Iraq     708,951     +5,173     13,483
29           29                Pakistan     583,916     +1,388     13,013
30           30             Philippines     582,223     +1,783     12,389
31           31             Switzerland     559,845     +1,223     10,013
32           32              Bangladesh     547,930       +614      8,428
33           33                 Morocco     484,753       +594      8,653
34           34                  Serbia     470,941     +4,056      4,491
35           35                 Austria     465,322     +2,553      8,625
36           36                 Hungary     439,900     +4,211     15,324
37           37                   Japan     434,356       +852      7,984
38           38                  Jordan     407,617     +5,335      4,793
39           39                     UAE     399,463     +2,692      1,269
41           41            Saudi Arabia     378,333       +331      6,510
43           43                Slovakia     314,359     +3,357      7,489
44           44                Malaysia     305,880     +1,745      1,148
45           45                 Belarus     290,447     +1,311      2,002
46           46                 Ecuador     289,472     +2,747     15,921
47           47                   Nepal     274,381        +87      2,778
48           48                 Georgia     271,739       +360      3,541
50           50                 Bolivia     250,557       +790     11,703
51           51                 Croatia     244,205       +747      5,555
52           52      Dominican Republic     240,773       +572      3,130
53           53              Azerbaijan     235,333       +319      3,230
55           55                 Ireland     221,189       +559      4,357
56           56              Kazakhstan     214,806       +717      2,540
57           57                 Denmark     212,798       +574      2,370
59           59               Lithuania     200,349       +503      3,281
60           60                  Greece     197,279     +2,697      6,597
61           61                  Kuwait     194,781     +1,409      1,097
62           62                Slovenia     192,266     +1,209      3,874
63           63                 Moldova     189,397     +1,550      4,026
64           64               Palestine     189,326     +2,017      2,078
67           67                 Armenia     172,816       +360      3,202
68           68                Honduras     171,758       +773      4,187
69           69                   Qatar     165,071       +471        260
70           70                Ethiopia     161,974     +1,161      2,391
73           73                    Oman     142,527       +358      1,583
74           74                 Myanmar     141,984        +19      3,199
76           76                   Libya     135,585       +618      2,219
77           77  Bosnia and Herzegovina     133,982       +894      5,174
79           79                 Algeria     113,593       +163      2,996
81           81                   Kenya     106,801       +331      1,866
82           82         North Macedonia     104,548       +802      3,156
83           83                S. Korea      90,816       +444      1,612
84           84                  Latvia      88,022       +919     1,654
85           85              Kyrgyzstan      86,356        +48      1,468
86           86                   Ghana      84,349       +326        611
88           88                  Zambia      80,090       +533      1,108
89           89              Uzbekistan      80,006        +45        622
90           90              Montenegro      77,493       +625      1,031
91           91                  Norway      72,653       +419        632
92           92                 Estonia      69,193     +1,467        615
94           94              Mozambique      60,395       +481        668
95           95               Singapore      59,979        +23         29
96           96                 Finland      59,442       +797        759
98           98              Luxembourg      55,902       +270        643
99           99             Afghanistan      55,797        +27      2,447
100         100                    Cuba      52,501       +914        333
102         102                 Namibia      39,297       +115        434
106         106                 Senegal      35,037       +205        896
108         108                  Malawi      32,229        +81      1,056
110         110               Australia      28,996        +10        909
112         112                     DRC      26,247       +197        711
113         113                Thailand      26,108        +35         84
114         114                 Jamaica      24,103       +265        435
115         115                   Malta      23,226       +233        321
125         125                  Guinea      16,154        +73         91
128         128                   Gabon      15,254       +405         88
134         134               Hong Kong      11,047        +14        200
135         135                 Andorra      10,948        +40        112
143         143             South Sudan       8,305       +161         97
145         145                 Somalia       7,727       +209        260
153         153                 Iceland       6,058         +3         29
162         162              San Marino       3,829        +38         75
167         167                Mongolia       3,032        +32          2
170         170           Liechtenstein       2,577         +1         54
171         171                 Vietnam       2,482        +10         35
172         172             New Zealand       2,384         +2         26
173         173                   Yemen       2,363        +21        643
175         175        Turks and Caicos       2,132        +17         14
183         183                  Taiwan         958         +3          9
184         184                Cambodia         878        +34
192         192             Isle of Man         511        +17         25
201         201                    Fiji          63         +4          2
220         220                   China      89,933        +10      4,636
221         221              33,720,845     +23,073    765,344      +1,378
222         222              25,223,160     +72,549    400,595        +742
223         223              18,134,879      +6,577    470,591        +128
224         224              34,442,286    +119,818    822,446      +2,724
225         225               3,949,024      +5,653    104,626         +64
228         228             115,522,246    +227,686  2,564,708      +5,036

In [123]:
import pandas
help(pandas)

Help on package pandas:

NAME
    pandas

DESCRIPTION
    pandas - a powerful data analysis and manipulation library for Python
    =====================================================================

    **pandas** is a Python package providing fast, flexible, and expressive data
    structures designed to make working with "relational" or "labeled" data both
    easy and intuitive. It aims to be the fundamental high-level building block for
    doing practical, **real world** data analysis in Python. Additionally, it has
    the broader goal of becoming **the most powerful and flexible open source data
    analysis / manipulation tool available in any language**. It is already well on
    its way toward this goal.

    Main Features
    -------------
    Here are just a few of the things that pandas does well:

      - Easy handling of missing data in floating point as well as non-floating
        point data.
      - Size mutability: columns can be inserted and deleted from DataFrame and
        higher dimensional objects
      - Automatic and explicit data alignment: objects can be explicitly aligned
        to a set of labels, or the user can simply ignore the labels and let
        `Series`, `DataFrame`, etc. automatically align the data for you in
        computations.
      - Powerful, flexible group by functionality to perform split-apply-combine
        operations on data sets, for both aggregating and transforming data.
      - Make it easy to convert ragged, differently-indexed data in other Python
        and NumPy data structures into DataFrame objects.
      - Intelligent label-based slicing, fancy indexing, and subsetting of large
        data sets.
      - Intuitive merging and joining data sets.
      - Flexible reshaping and pivoting of data sets.
      - Hierarchical labeling of axes (possible to have multiple labels per tick).
      - Robust IO tools for loading data from flat files (CSV and delimited),
        Excel files, databases, and saving/loading data from the ultrafast HDF5
        format.
      - Time series-specific functionality: date range generation and frequency
        conversion, moving window statistics, date shifting and lagging.

PACKAGE CONTENTS
    _config (package)
    _libs (package)
    _testing
    _typing
    _version
    api (package)
    arrays (package)
    compat (package)
    conftest
    core (package)
    errors (package)
    io (package)
    plotting (package)
    testing
    tests (package)
    tseries (package)
    util (package)

SUBMODULES
    _hashtable
    _lib
    _tslib
    offsets

FUNCTIONS
    __getattr__(name)
        # GH 27101

DATA
    IndexSlice = <pandas.core.indexing._IndexSlice object>
    NA = <NA>
    NaT = NaT
    __docformat__ = 'restructuredtext'
    __git_version__ = '2cb96529396d93b46abab7bbc73a208e708c642e'
    describe_option = <pandas._config.config.CallableDynamicDoc object>
    get_option = <pandas._config.config.CallableDynamicDoc object>
    options = <pandas._config.config.DictWrapper object>
    reset_option = <pandas._config.config.CallableDynamicDoc object>
    set_option = <pandas._config.config.CallableDynamicDoc object>

VERSION
    1.2.4

FILE
    c:\users\user\anaconda3\lib\site-packages\pandas\__init__.py